USB_VID = 0x1209
USB_PID = 0x0001
USB_PRODUCT = "DrawBot"
USB_MANUFACTURER = "SensiLab"

CHIP_VARIANT = SAMD21J18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0

SUPEROPT_GC = 0
