#include "shared-bindings/board/__init__.h"

STATIC const mp_rom_map_elem_t board_global_dict_table[] = {
    { MP_ROM_QSTR(MP_QSTR_LED_R),      MP_ROM_PTR(&pin_PB07) },
    { MP_ROM_QSTR(MP_QSTR_LED_G),      MP_ROM_PTR(&pin_PB05) },
    { MP_ROM_QSTR(MP_QSTR_BATT_LVL_1), MP_ROM_PTR(&pin_PB22) },
    { MP_ROM_QSTR(MP_QSTR_BATT_LVL_2), MP_ROM_PTR(&pin_PB11) },
    { MP_ROM_QSTR(MP_QSTR_BATT_LVL_3), MP_ROM_PTR(&pin_PB12) },
    { MP_ROM_QSTR(MP_QSTR_BATT_LVL_4), MP_ROM_PTR(&pin_PB13) },
    { MP_ROM_QSTR(MP_QSTR_IR_CTRL_1),  MP_ROM_PTR(&pin_PA13) },
    { MP_ROM_QSTR(MP_QSTR_IR_CTRL_2),  MP_ROM_PTR(&pin_PA12) },
    { MP_ROM_QSTR(MP_QSTR_TOF1_EN),    MP_ROM_PTR(&pin_PA27) },
    { MP_ROM_QSTR(MP_QSTR_TOF2_EN),    MP_ROM_PTR(&pin_PA14) },
    { MP_ROM_QSTR(MP_QSTR_TOF3_EN),    MP_ROM_PTR(&pin_PB00) },
    { MP_ROM_QSTR(MP_QSTR_LED_EN),     MP_ROM_PTR(&pin_PA15) },
    { MP_ROM_QSTR(MP_QSTR_TCS_EN),     MP_ROM_PTR(&pin_PB01) },
    { MP_ROM_QSTR(MP_QSTR_MOTOR_EN),   MP_ROM_PTR(&pin_PB04) },
    { MP_ROM_QSTR(MP_QSTR_M1_DIRA),    MP_ROM_PTR(&pin_PB14) },
    { MP_ROM_QSTR(MP_QSTR_M1_DIRB),    MP_ROM_PTR(&pin_PB15) },
    { MP_ROM_QSTR(MP_QSTR_M2_DIRA),    MP_ROM_PTR(&pin_PB16) },
    { MP_ROM_QSTR(MP_QSTR_M2_DIRB),    MP_ROM_PTR(&pin_PB17) },
    { MP_ROM_QSTR(MP_QSTR_TCS_INT),    MP_ROM_PTR(&pin_PA16) },
    { MP_ROM_QSTR(MP_QSTR_HOST_INT_1), MP_ROM_PTR(&pin_PA17) },
    { MP_ROM_QSTR(MP_QSTR_HOST_INT_2), MP_ROM_PTR(&pin_PA10) },
    { MP_ROM_QSTR(MP_QSTR_TOF1_INT),   MP_ROM_PTR(&pin_PB02) },
    { MP_ROM_QSTR(MP_QSTR_TOF2_INT),   MP_ROM_PTR(&pin_PB03) },
    { MP_ROM_QSTR(MP_QSTR_TOF3_INT),   MP_ROM_PTR(&pin_PA20) },
    { MP_ROM_QSTR(MP_QSTR_M1_ENC_A),   MP_ROM_PTR(&pin_PA21) },
    { MP_ROM_QSTR(MP_QSTR_M1_ENC_B),   MP_ROM_PTR(&pin_PB06) },
    { MP_ROM_QSTR(MP_QSTR_M2_ENC_A),   MP_ROM_PTR(&pin_PB23) },
    { MP_ROM_QSTR(MP_QSTR_M2_ENC_B),   MP_ROM_PTR(&pin_PA28) },
    { MP_ROM_QSTR(MP_QSTR_BMX_INT1),   MP_ROM_PTR(&pin_PA09) },
    { MP_ROM_QSTR(MP_QSTR_BMX_INT2),   MP_ROM_PTR(&pin_PB10) },
    { MP_ROM_QSTR(MP_QSTR_IR1),        MP_ROM_PTR(&pin_PB08) },
    { MP_ROM_QSTR(MP_QSTR_IR2),        MP_ROM_PTR(&pin_PB09) },
    { MP_ROM_QSTR(MP_QSTR_IR3),        MP_ROM_PTR(&pin_PA04) },
    { MP_ROM_QSTR(MP_QSTR_IR4),        MP_ROM_PTR(&pin_PA05) },
    { MP_ROM_QSTR(MP_QSTR_IR5),        MP_ROM_PTR(&pin_PA06) },
    { MP_ROM_QSTR(MP_QSTR_BATTERY),    MP_ROM_PTR(&pin_PA07) },
    { MP_ROM_QSTR(MP_QSTR_M1_PWM),     MP_ROM_PTR(&pin_PA11) },
    { MP_ROM_QSTR(MP_QSTR_M2_PWM),     MP_ROM_PTR(&pin_PA18) },
    { MP_ROM_QSTR(MP_QSTR_S1_PWM),     MP_ROM_PTR(&pin_PA19) },
    { MP_ROM_QSTR(MP_QSTR_NEOPIXEL),   MP_ROM_PTR(&pin_PA08) },

    { MP_ROM_QSTR(MP_QSTR_SDA),         MP_ROM_PTR(&pin_PA22) },
    { MP_ROM_QSTR(MP_QSTR_SCL),         MP_ROM_PTR(&pin_PA23) },
    { MP_ROM_QSTR(MP_QSTR_SDA_SLAVE),   MP_ROM_PTR(&pin_PB30) },
    { MP_ROM_QSTR(MP_QSTR_SCL_SLAVE),   MP_ROM_PTR(&pin_PB31) },

    { MP_ROM_QSTR(MP_QSTR_DAC),        MP_ROM_PTR(&pin_PA02) },
    { MP_ROM_QSTR(MP_QSTR_VREF),       MP_ROM_PTR(&pin_PA03) },

    { MP_ROM_QSTR(MP_QSTR_I2C),        MP_ROM_PTR(&board_i2c_obj) },
    { MP_ROM_QSTR(MP_QSTR_SPI),        MP_ROM_PTR(&board_spi_obj) },
    { MP_ROM_QSTR(MP_QSTR_UART),       MP_ROM_PTR(&board_uart_obj) }
};
MP_DEFINE_CONST_DICT(board_module_globals, board_global_dict_table);
